config/routes.rb
GameBlog3211::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/zinbosignup',  :to => 'users#new'
  match '/zinbosignin',  :to => 'sessions#new'
  match '/zinbosignout', :to => 'sessions#destroy', :via => :delete

  resources :posts do
    resources :comments
  end
  
  match '/blog' =>  'posts#index',   :as =>:blog

  match "about_me" => "static_pages#about_me"
  match "cv" => "static_pages#cv"

   root :to => 'posts#index'
   
  get "portfolio/masters"
  get "portfolio/game_jam_york"
  get "portfolio/eotBK"
  get "portfolio/untitled"
  get "portfolio/electric_justice"
  match 'portfolio' => "portfolio#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  validates_presence_of :body, :title
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, :presence => true, :length => { :maximum => 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true,
                    :format => { :with => VALID_EMAIL_REGEX },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, :length => { :minimum => 6 }
  validates :password_confirmation, :presence => true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.base64.tr("+/", "-_")
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  include SessionsHelper
  
  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(user_params)
    respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js 
    end
  end
  
  private
  def user_params
      params.require(:comment).permit(:user, :post, :body)
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
  
  def masters
  end

  def game_jam_york
  end

  def eotBK
  end

  def untitled
  end

  def electric_justice
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, :only => [:show, :edit, :update, :destroy]
  before_filter :signed_in_user, :only => [:edit, :new, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5).order("updated_at DESC")
  end

  def url_for(options)
    super(options)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render 'show', :status => :created, :location => @post }
      else
        format.html { render 'new' }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about_me
  end

  def cv
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.email == "shane@zinbo.co.uk"
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to root_url
      else
        render 'new'
      end  
      else
        flash.now[:error] = 'Registrations are not taking place right now.'
        render 'new'
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Shane's Game Development Blog"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, :notice => "Please sign in."
    end
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private

    def clear_return_to
      session.delete(:return_to)
    end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="col-xs-12">
	<p>
		<strong>
			<%= comment.user %>
		</strong>
		<br />
		Posted <%= time_ago_in_words(comment.created_at) %> ago
		<br/>
	    <%= comment.body %>
    </p>
</div>

app/views/comments/create.js.erb
$('#comments').html("<%=j render @post.comments %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand header_text" href="/">Shane Jennings</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav pull-right">
              <li class="header_text"><%= link_to "Quest Log", "/portfolio" %></li>
              <li class="header_text"><%= link_to "Bio", "/about_me" %></li>
              <li class="header_text"><%= link_to "Stats", "/cv" %></li>
              <% if signed_in? %>
              <li>
                  <%= link_to "Sign out", zinbosignout_path, :method => "delete" %>
                </li>
                <% end %>
              <li class="dropdown">
	              <a href="#" class="dropdown-toggle header_text" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false">
        Contact Me <b class="caret"></b>
	              </a>
	              <ul class="dropdown-menu">
	                <li><%= link_to "<i class=\"fa fa-envelope fa-2x\"></i>".html_safe, "mailto:shanepjennings@gmail.com"%></li>
              <li><%= link_to "<i class=\"fa fa-linkedin-square fa-2x\"></i>".html_safe, "https://uk.linkedin.com/in/shanepjennings"%></li>
              <li><%= link_to "<i class=\"fa fa-twitter fa-2x\"></i>".html_safe, "https://www.twitter.com/superzinbo"%></li>
              <li><%= link_to "<i class=\"fa fa-github fa-2x\"></i>".html_safe, "https://github.com/zinbo"%></li>
              <li><%= link_to "<i class=\"fa fa-bitbucket fa-2x\"></i>".html_safe, "https://bitbucket.org/zinbo"%></li>
	                
	              </ul>
	            </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/portfolio/electric_justice.html.erb
<h1>Electric Justice</h1>
<p class="centre">Status: <span class="halted">Halted</span></p>
<div class="container">
  <div class="row">
  	<div class="col-xs-4">
  		<h3> Overview </h3>
  		<p>I created a web application using the Ruby on Rails framework. The web application is for my guild in World of Warcraft, Electric Justice. 
  			The web application was created to manage the guild, and to provide an overview of the guild to guild members, as well as raise awareness in order to recruit new members.
  			The web application has a forum, a poll system, a roster showing all guild members, raid progression, and a news page. There are plans to integrate the guild bank and in-game calendar in the future.</p>
		<p>The web application communicates with the <%= link_to "World of Warcraft Community Web API", "http://blizzard.github.io/api-wow-docs/" %> in order to pull down information
			on the guild and its members. The API is RESTful, and returns information on characters, guilds, items, raid, and more in JSON when a get request is performed.</p>
			<p>The web application also used third-party applications written in Lua in order to track in-game events which were not made visible by the API.</p>
			<p> The web application is currently hosted on heroku <%= link_to "here", "http://electric-justice.herokuapp.com/"%>, and the code can be viewed on my github page
				<%= link_to "here", "https://github.com/Zinbo/electric_justice"%>. </p>
      <div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/exampleJSON.png"><img width="100%" src="/assets/exampleJSON.png"/></a>
	      	<p class="description descriptive-text">JSON returned by the WoW API for the character Zinbo</p>
		</div>
  	</div>
  	<div class="col-xs-4">
      <h3>Challenges</h3>
      <p>This was the first non-trivial web application which I have made by myself, so the learning curve was quite steep. It was also my first time using both Ruby and Rails, so there
      	was the added complexity of learning both a new programming language and a framework. </p>
      	<p> There was also the added complexity of some information in the game not being made visible to the API. This meant that addons had to be used which could
      		write information from the game to a file and then that file be uploaded to the web application. As part of Blizzard's terms and conditions addons cannot mine for data
      		and send via the web, hence the need to save to a file. The problem here was that I could not find any addons which did exactly what I wanted, which meant that I
      		started writing my own. </p> 
      		<p>WoW addons are written in Lua, which I had no previous experience of, apart from a very simple addon which random selects mounts from the
      		characters current collection (which can be seen here). Therefore I had to learn more about Lua in order to start developing addons which could retrieve information
      		on items in the guild bank and the in-game guild calendar.</p>
	  <p></p>
	</div>
	<div class="col-xs-4">
		<div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/rosterPage.png"><img  width="100%" src="/assets/rosterPage.png"/></a>
	      	<p class="description descriptive-text">The roster page, showing a paginated list of the guild members</p>
		</div>
		<h3>Outcome</h3>
      	<p>I have halted progress on this project as I have suspended my WoW subscription due to my university work load. However I have learnt a lot so far from this project.</p>
      	<p>I have learnt how to create web applications using Ruby on Rails - learning both the Ruby language and the Rails framework. I feel I now have a good understanding 
      		of both of these (this web site written using Ruby on Rails!). </p>
  		<p>Whilst I alreaady had previous experiences with Javascript, HTML, and CSS, this project really helped to reinforce my knowledge, specifically on the use of JavaScript when
  			trying to contain most of the logic in the model, as dictated by the Active Record Pattern. </p>
  		<p>I also feel I have a better understanding of web development principles, such as the MVC and active record pattern, AJAX, and the use of authentication systems in web applications. </p>
  		<p>I was able to get some more experience with Lua. I'm hoping that I will be able to strengthen my knowledge of Lua even more once I start this project up again. </p>
	</div>
  </div>
</div>

app/views/portfolio/eotBK.html.erb
<h1>Eternity of the Broken Kings</h1>
<p style="text-align:center">Status: <span class="complete">Complete</span></p>
<div class="container">
  <div class="row">
  	<div class="col-xs-4">
  		<h3> Overview </h3>
  		<p>I created a horror/action text-based game based on the book "Eternity of the Star Witch". The game works by giving the player a description of their current state nad giving them multiple options to choose from.
			Some options progress the player further in the game whilst others have the player meet their demise. When a player chooses the wrong action they are brought back to the state that they chose from, 
			except for when the player is in the final boss battle, where the player is brought back to the start of the battle.</p>
			<p>The game was written in C++. The game works by taking in a text file, containing all of the states, options, and consequences of the game, and storing them in memory. The player then chooses options until
			they reach the end of the game. </p>
		<p> 
      <div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/mcts-tree.png"><img width="100%" src="/assets/mcts-tree.png"/></a>
	      	<p class="description descriptive-text">An example of a MCTS tree</p>
		</div>
  	</div>
  	<div class="col-xs-4">
      <h3>Challenges</h3>
      <p>This project was mainly used as a learning experience in order for me to better understand C++. I had previously read a few books on C++ and tried a few tutorials (including creating pong using SFML) but had
	  never tried anything substantial. Whilst I had plenty of development experience before, principles such as managing my own garbage collection, pointers, and references, in practice, were relatively new to me.
	  I knew that I wanted to implement my Master's project in C++, so I wanted to make sure that I had a good foundation of knowledge.</p>
	  <p></p>
	</div>
	<div class="col-xs-4">
		<div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/LoWGame.jpg"><img  width="100%" src="/assets/LoWGame.jpg"/></a>
	      	<p class="description descriptive-text">A Lords of War game in play on the board</p>
		</div>
		<h3>Outcome</h3>
      	<p>The project is now complete and can be viewed HERE.</p>
		<p>I feel this project really helped reinforce my understanding of some of the main principles of C++. I was also able to compile a "cheat sheet" containing all of the information I came across regarding C++.
		The project really helped give me a good start towards using C++ for my Master's project.</p>
	</div>
  </div>
</div>

app/views/portfolio/game_jam_york.html.erb
<h1>Departure</h1>
<p class="centre">Status: <span class="complete">Complete</span></p>
<div class="container">
  <div class="row">
  	<div class="col-xs-4">
  		<h3> Overview </h3>
  		<p>Departure was made during the University of York's first Game Jam. A game jam is an opportunity to, as a team, create a game in 48 hours based on a theme given on the day.
			At the end of the 48 hours each team's game is played and evaluated by judges and other teams based on criteria such as relation to the theme, quality of music, and other others, 
			with the highest scoring team winning.</p>
		<p> I jonied a team of four other people at the event. The theme for the Game Jam was the Grand Départ, so we decided to make a space-themed turn-based strategy game called departre.
			The basic story line of the game was that the player was the cpatain of a spaceship charged with colonising planets, due to Earth becoming inhabitable because of war. </p>
		<p> The game mechanics were quite simple. the player could move the ship once per turn to different planets. Once at a planet the player could colonise the planet (if the planet had not already been colonised) by
			'paying' in resources, where resources were people, food, and money. Once a planet was owned the player could withdraw and deposity resources to the planet, providing the player was current situated at that planet.
			People in the planet would use up food resources, but also create resources. The game also had a shop, which the player could access to sell and buy resources. </p>
		<p>The players score was based on the overall happiness of colonised people at the end of each turn. If people had enough food on their planet then the people were happy and the players score increased (relative to the
			amount of happy people). However if peeople did not have enough food on their planet then the people would be unhappy and the players score decreased (relative to the amount of unhappy people). 
			The aim of the game was to, within a limited number of turns achieve a score of 100. </p>
		<p>The game was written in C#, using the unity engine. Unfortunately, the source code is not available online. </p>
  	</div>
  	<div class="col-xs-4">
      <h3>Challenges</h3>
      <p>One of the biggest (and most obvious) challenges of this project was being able to make a working game within 48 hours. It was difficult as we had a lot of ideas for features, however we did not have enough time
	  to implement them. It was very easy to underestimate how much time implementing a whole game came take. We ended up putting a lot of work into the game, where I personally spent roughly 30 out of the 48 hours coding.</p>
	  <p>I also had limited experience using C# and unity, so I had to both learn new aspects of Unity whilst trying to make the game. My other team members also had limited experience with both C# and Unity, which definitely
	  slowed us down.<p/>
	  <p>This project not only required the technical skills to making a game, but also required good planning and social skills, in order to have a working game within 48 hours.</p>
	<div class="portfolio-picture">	
      	<a class="fancybox" rel="group" href="/assets/mcts-tree.png"><img width="100%" src="/assets/mcts-tree.png"/></a>
      	<p class="description descriptive-text">An example of a MCTS tree</p>
	</div>
	</div>
	<div class="col-xs-4">
		<div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/LoWGame.jpg"><img  width="100%" src="/assets/LoWGame.jpg"/></a>
	      	<p class="description descriptive-text">A Lords of War game in play on the board</p>
		</div>
		<h3>Outcome</h3>
      	<p>We made a working game at the end of the 48 hours, and won 2nd place out of 10 teams. </p>
      	<p>This project gave me a good understanding of what it was like to make a game under pressure and how important planning can be. 
		I realised that we should have developed the game in an incremental fashion, starting from the most basic of features and then adding more per iteration, rather than just diving in. Whilst diving in may work for
		individual projects, this does not work as team.</p>
		<p>I felt this project also gave me a much better understanding of the Unity engine, and C#. </p>
		<p>All in all, I really enjoyed the Game Jam, and would love to participate in another one in the future.</p>
	</div>
  </div>
</div>

app/views/portfolio/index.html.erb
<div class="jumbotron">
	<h1>Quest Log</h1>
	<h2>Portfolio of work</h2>
</div>
<div class="container">
      <!-- Example row of columns -->
      <div class="row">
      	<div class="col-md-4">
          <h3>Master's Project</h3>
          <p>My master's project concerns developing an AI agent using Monte Carlo Tree Search and the Minimax algorithm in order to play the trading card game Lords of War.</p>
          <p><%= button_to "Learn more »", "portfolio/masters", :class=>"btn btn-primary", :method => "get" %></p>
        </div>
        <div class="col-md-4">
          <h3>Game Jam York</h3>
          <p>Took part in the University of York's first <%= link_to "Game Jam", "http://www.gamejamyork.co.uk/"%> with a team and developed a turn-based strategy space game, winning second place. </p>
          <p><%= button_to "Learn more »", "portfolio/game_jam_york", :class=>"btn btn-primary", :method => "get" %></p>
        </div>
        <div class="col-md-4">
          <h3>Eternity of the Broken Kings</h3>
          <p>A horror/action text adventure game based on the book "Eternity of the Star Witch".</p>
          <p><%= button_to "Learn more »", "portfolio/eotBK", :class=>"btn btn-primary", :method => "get" %></p>
       </div>
    </div>
    <div class="row">
    	<div class="col-md-4">
          <h3>UnTitled</h3>
          <p>A platformer using the Marmalade C++ SDK. </p>
          <p><%= button_to "Learn more »", "portfolio/untitled", :class=>"btn btn-primary", :method => "get" %></p>
       </div>
       <div class="col-md-4">
          <h3>Electric Justice</h3>
          <p>An web application for my guild on World of Warcraft</p>
          <p><%= button_to "Learn more »", "portfolio/electric_justice", :class=>"btn btn-primary", :method => "get" %></p>
       </div>
   </div>

app/views/portfolio/masters.html.erb
<h1>Master's Project</h1>
<p class="centre">Status: <span class="ongoing">Ongoing</span></p>
<div class="container">
  <div class="row">
  	<div class="col-xs-4">
  		<h3> Overview </h3>
  		<p>My Master's project is on using the search algorithms Monte Carlo Tree Search and Minimax in order to develop a player for the card game game <%= link_to "Lords of War", "http://lords-of-war.com/"%>. The main body of the project is to compare the different techniques and how the inclusion of heuristic knowledge increases (or decreases) the strength of the player.  </p>
      <div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/mcts-tree.png"><img width="100%" src="/assets/mcts-tree.png"/></a>
	      	<p class="description descriptive-text">An example of a MCTS tree</p>
		</div>
  	</div>
  	<div class="col-xs-4">
      <h3>Challenges</h3>
      <p>Lords of War is what is known as as a stochastic imperfect information game. It is stochastic as the player must pick up cards from a shuffled deck, and it is imperfect information as you cannot see your opponent's hand, therefore you do not have a perfect view of the game state. This makes developing an AI player challenging. </p>
	  <p>This project also requires a good understanding of C++. C++ is used in order to implement a fast and efficient player, as the amount of information the AI player must examine becomes very large due to the branching factor when looking at future moves.</p>
	</div>
	<div class="col-xs-4">
		<div class="portfolio-picture">	
	      	<a class="fancybox" rel="group" href="/assets/LoWGame.jpg"><img  width="100%" src="/assets/LoWGame.jpg"/></a>
	      	<p class="description descriptive-text">A Lords of War game in play on the board</p>
		</div>
		<h3>Outcome</h3>
      	<p>The project is still ongoing and isn't due to be finished until 05/05/2014.</p>
      	<p>So far I have learnt more about different AI techniques, such as MCTS, and more about game theory. I am currently implementing a Minimax player in C++, which has helped strengthen my knowledge of C++.</p>
	</div>
  </div>
</div>

app/views/portfolio/untitled.html.erb
<h1>Untitled</h1>
<p class="centre">Status: <span class="ongoing">Ongoing</span></p>
<div class="container">
  <div class="row">
  	<h3 class="centre">Information coming soon!</h3>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 >Zinbo the Master Engineer</h1>
  <h2>An aspiring games developer's journey to end game</h2>

  </div>
</div>
<%if signed_in? %>
	<%= link_to "New post", new_post_path %>
<%end%>
<%= will_paginate %>
<% @posts.each do |post| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3  class="panel-title" style="float: left;"><%= post.title %></h3>
     <h3 style="float: right;" class="panel-title"><%= time_ago_in_words(post.created_at) %> ago.</h3>
     <div style="clear: both;"></div>
  </div>
  <div class="panel-body">

<%= RedCloth.new(post.body).to_html.html_safe %> 
  </div>
</div>
	<% if signed_in? %>
		<%= link_to 'Edit', edit_post_path(post) %>
		<%= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
	<% end %>
<% end %>
<%= will_paginate %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3  class="panel-title" style="float: left;"><%= @post.title %></h3>
     <h3 style="float: right;" class="panel-title"><%= time_ago_in_words(@post.created_at) %> ago.</h3>
     <div style="clear: both;"></div>
  </div>
  <div class="panel-body">

<%= RedCloth.new(@post.body).to_html.html_safe %> 
  </div>
</div>

 <h3>Comments</h3>
<div id="comments" class="container">
	<div class="row">
		<%= render :partial => @post.comments%>
	</div>
</div> 

<%= form_for [@post, Comment.new], :remote => true do |f| %>
        <p>
        	<h3> Leave a comment </h3>
                <%= f.label :user%> <%= f.text_field :user %><br />
                <%= f.text_area :body, :cols=>"30" %>
        </p>
        <p><%= f.submit "Add comment" %></p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>